### ISSUE TITLE
当实体类指定基类EntityTree时，主类多EntityTree

### ISSUE THREAD

**Issue by abc54288** [NewLifeX/NewLife.XCode#26]
![image](https://github.com/NewLifeX/NewLife.XCode/assets/3676387/ebd2a34a-5847-4794-98f8-f7990b50d1d8)
![xcodetool](https://github.com/NewLifeX/NewLife.XCode/assets/3676387/d23ccb38-151f-4596-8c21-07b365c0fa19)
![image](https://github.com/NewLifeX/NewLife.XCode/assets/3676387/0065e360-3a12-48fc-ba53-424403ed991b)

**Comment by nnhy** [comment]
2023.603的代码生成器比较老，更换为最新版本试试。
在XCode/Membership目录下与一个xcodetool.exe，或者自己编译发布xcodetool

**Comment by abc54288** [comment]
自己编译发布的生成没问题。我原来都是在https://newlifex.com/xcode/model下载的，所以是旧版。
