### ISSUE TITLE
无法自动下载Plugins插件

### ISSUE THREAD

**Issue by PikachuCN** [NewLifeX/NewLife.XCode#55]
按照教程操作，会在插入时卡死，Plugins无法下载。用了代理或者没代理也不行。只能复制老项目的Plugins目录。这样就正常。

**Comment by PikachuCN** [comment]
我只是做了一个最简单的查询，winform就会卡死。附上日志记录：

#Software: XcoderTest
#ProcessID: 11904 x64
#AppDomain: XcoderTest
#FileName: C:\Users\dengz\source\repos\XcoderTest\XcoderTest\bin\Debug\net8.0-windows\XcoderTest.exe
#BaseDirectory: C:\Users\dengz\source\repos\XcoderTest\XcoderTest\bin\Debug\net8.0-windows\
#TempPath: C:\Users\dengz\AppData\Local\Temp\
#CommandLine: C:\Users\dengz\source\repos\XcoderTest\XcoderTest\bin\Debug\net8.0-windows\XcoderTest.dll
#ApplicationType: WinForm
#CLR: 8.0.8, .NET 8.0.8
#OS: Microsoft Windows NT 10.0.22631.0, HOME/dengz
#CPU: 16
#GC: IsServerGC=False, LatencyMode=Interactive
#ThreadPool: Min=32/32, Max=32767/1000, Available=32765/1000
#SystemStarted: 1.00:31:00
#Date: 2024-11-30
#详解：https://newlifex.com/core/log
#字段: 时间 线程ID 线程池Y/网页W/普通N/定时T 线程名/任务ID 消息内容
#Fields: Time ThreadId Kind Name Message
01:28:16.195 01 N - NewLife.Core v11.0.2024.1113 Build 2024-11-13 .NET 8.0
01:28:16.198 01 N - NewLife组件核心库 ©2002-2024 NewLife
01:28:16.198 01 N - XcoderTest v1.0.0 Build 2000-01-01 .NET 8.0
01:28:16.198 01 N - XcoderTest 
01:28:16.198 01 N - XCode v11.16.2024.1114 Build 2024-11-14 .NET Standard 2.1
01:28:16.198 01 N - NewLife数据中间件 ©2002-2024 NewLife
01:28:16.198 01 N - 当前配置为输出SQL日志，如果觉得日志过多，可以修改配置关闭[Config/XCode.config:ShowSQL=false]。
01:28:16.219 01 N - 自动为[DB]设置SQLite连接字符串：Data Source=Data\DB.db;Migration=On
01:28:16.557 01 N - [DB]待检查数据表：UserInfo
01:28:16.562 01 N - System.Data.SQLite.dll不存在或平台版本不正确，准备联网获取 http://x.newlifex.com/
01:28:16.565 01 N - 下载链接 http://x.newlifex.com/，目标 System.Data.SQLite.win-x64,System.Data.SQLite.win,System.Data.SQLite_net80,System.Data.SQLite_net70,System.Data.SQLite_net60,System.Data.SQLite_net50,System.Data.SQLite_netstandard21,System.Data.SQLite_netstandard20,System.Data.SQLite
01:28:16.577 01 N - WebClientX.Get http://x.newlifex.com/?auth_key=1732901296-455171-0-c80f9080d098c2debb6a504f044772ac

**Comment by nnhy** [comment]
WinForm项目+卡死，大概率就是这里的同步调用异步有问题。
最近为了全面优化高并发时线程饥渴问题，减少了一些Task.Run包装，可能跟这个有关。
我检查一下，感谢反馈！

**Comment by nnhy** [comment]
强制启用CA2007规则，任何层级，只要是通用库代码，await时都应该调用ConfigureAwait(false)。
https://github.com/NewLifeX/X/commit/b93a820372233668bd919991768c0a3bafd33dff
